
export const foodCourt = [
    {
      id:1,
      image: '@/assets/images/foodcourt1.jpeg',
      name: 'Gourmet Plaza',
      distance: '1.2 km',
      location: 'Downtown',
      priceRange: 'Expensive',
      famousFor: 'International Cuisine',
      landmark: 'Near Central Park',
    },
    {
      id:2,
      image: '@/assets/images/foodcourt1.jpeg',
      name: 'Budget Bites',
      distance: '0.8 km',
      location: 'Market Street',
      priceRange: 'Budget Friendly',
      famousFor: 'Street Food',
      landmark: 'Opposite City Library',
    },
    {
      id:3,
      image: '@/assets/images/foodcourt1.jpeg',
      name: 'Family Feast',
      distance: '2.0 km',
      location: 'Suburb Area',
      priceRange: 'Moderate',
      famousFor: 'Family-friendly atmosphere',
      landmark: 'Next to Green Mall',
    },
    {
      id:4,
      image: '@/assets/images/foodcourt1.jpeg',
      name: 'Veggie Delight',
      distance: '1.5 km',
      location: 'Main Avenue',
      priceRange: 'Budget Friendly',
      famousFor: 'Vegetarian and Vegan Options',
      landmark: 'Across from City Hospital',
    },
    {
      id:5,
      image: '@/assets/images/foodcourt1.jpeg',
      name: 'Quick Eats',
      distance: '0.5 km',
      location: 'Business District',
      priceRange: 'Moderate',
      famousFor: 'Fast Food and Snacks',
      landmark: 'Near Tech Hub',
    },
    {
      id:6,
      image: '@/assets/images/foodcourt1.jpeg',
      name: 'Seafood Haven',
      distance: '3.0 km',
      location: 'Coastal Road',
      priceRange: 'Expensive',
      famousFor: 'Fresh Seafood',
      landmark: 'By the Marina',
    },
    {
      id:7,
      image: '@/assets/images/foodcourt1.jpeg',
      name: 'Sweet Treats',
      distance: '1.8 km',
      location: 'Old Town',
      priceRange: 'Budget Friendly',
      famousFor: 'Desserts and Pastries',
      landmark: 'Next to the Clock Tower',
    },
    {
      id:8,
      image: '@/assets/images/foodcourt1.jpeg',
      name: 'Healthy Haven',
      distance: '2.5 km',
      location: 'Eco Park',
      priceRange: 'Moderate',
      famousFor: 'Organic and Health Foods',
      landmark: 'Near Botanical Gardens',
    },
    {
      id:9,
      image: '@/assets/images/foodcourt1.jpeg',
      name: 'Night Bazaar',
      distance: '2.2 km',
      location: 'City Center',
      priceRange: 'Budget Friendly',
      famousFor: 'Late-night Snacks',
      landmark: 'Next to Night Market',
    },
    {
      id:10,
      image: '@/assets/images/foodcourt1.jpeg',
      name: 'Spice Route',
      distance: '0.9 km',
      location: 'Cultural District',
      priceRange: 'Moderate',
      famousFor: 'Asian Cuisine',
      landmark: 'Near Art Museum',
    }
  ];
  